name: CI
on: [ push ]
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Install Pandoc
          run: sudo apt install -y pandoc

        - name: Checkout
          uses: actions/checkout@v2

        - name: Build
          run: find ./ -iname "*.md" ! -name 'README.md' -type f -exec sh -c 'pandoc -f markdown -t html --self-contained --css=pandoc.css "${0}" -o "web/${0%.md}.html" --metadata pagetitle="${0%.md}"' {} \;

        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@v4.2.3
          with:
            branch: gh-pages
            folder: web